config/routes.rb
Rails.application.routes.draw do
  resources :words do
  end
  #get 'words', to: 'words#index', as: 'words'
  #get 'word/:id', to: 'words#edit', as: 'edit_word'
  #get 'words/update'
  #get 'words/new'
  #get 'words/create'
  root 'mirror#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/word.rb
class Word < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/mirror_controller.rb
class MirrorController < ApplicationController
  include ApplicationHelper
  def index
    @word = Word.find(rand(1..Word.maximum(:id)))
      @weather = get_weather
      unless @weather.nil?
          @max_temp = @weather['main']["temp_max"].to_i
          @min_temp = @weather['main']["temp_min"].to_i
          @temp = @weather['main']["temp"].to_i
          @feels_like = @weather['main']["feels_like"].to_i
          @image = @weather['weather'].first['icon']
      else
      
      end
    @news_german = get_news('Deutschland')
    #@news_lithuania = get_news('Litauen')
    @news_economics = get_news('Wirtschaft')


# %iframe{:frameborder => "0", :height => "600", :scrolling => "no", :src => "https://calendar.google.com/calendar/embed?src=gintare.lideikyte%40googlemail.com&ctz=Europe%2FBerlin", :style => "border: 0", :width => "800"}
  end
  
  private
  def request_api(url)
    response = Excon.get(
      url,
      headers: {
        'X-RapidAPI-Host' => URI.parse(url).host,
        #'X-RapidAPI-Key' => ENV.fetch('082a03e1732d575e462eddb2dc705497')
      }
    )
    return nil if response.status != 200
    JSON.parse(response.body)
  end
  
  def get_weather
    logger.info('get_weather')
    api_key = Rails.application.credentials.api_key
    request_api(
      "http://api.openweathermap.org/data/2.5/weather?q=Meersburg&exclude=daily&units=metric&appid=#{api_key}"
    )
  end

  require 'net/http'
  def get_news(search)
    api_key = Rails.application.credentials.api_key_news
    date = DateTime.now.strftime('%Y-%m-%d')
    uri = URI("http://newsapi.org/v2/everything?q=#{search}&from=#{date}&sortBy=publishedAt&apiKey=#{api_key}")
    res = Net::HTTP.get_response(uri)

    JSON.parse(res.body)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  def index
    @words= Word.all
  end

  def edit
    @word = Word.find(params[:id])
  end

  def update
    @word = Word.find(params[:id])
    if @word.update(lt: params[:lt], de: params[:de])
      flash[:success] = 'Gespeichert'
    end
    redirect_to words_path
  end

  def new
    @word = Word.new
  end

  def create
    @word = Word.new(lt: params[:lt], de: params[:de])
    if @word.save
      flash[:success] = 'Gespeichert'
    end
    redirect_to words_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : "Spiegel" %></title>
  <script language="JScript" type="text/jscript">
    setTimeout("location.reload();",60*60000);
  </script>
  <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "About Sharks" %>">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
</head>

<body class="body">

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/mirror/index.html.haml
%script{:language => "JScript", :type => "text/jscript"}
  window.setTimeout("ZeitAnzeigen()", 1000);

.row
  .col
    = image_tag("#{@image}.png", class:'mt-3', style: "width: 100%")
  .col
    %h1.temp.text-left.mt-3= "#{@temp}°C"
  .col

  .col
    %h1.text-right#Uhr{:style => "font-size:300%;font-weight:bold"}
    %h2.text-right= DateTime.now.strftime('%d.%m.%Y')
    %h2.text-right= ['Montag', 'Dienstag', 'Mittwoch', 'Donnerstag', 'Freitag', 'Samstag', 'Sonntag'][DateTime.now.wday-1]
    %h2.text-right= ['Pirmadienis', 'Antradienis', 'Trečiadienis', 'Ketvirtadienis', 'Penktadienis', 'Šeštadienis', 'Sekmadienis'][DateTime.now.wday-1]
.row
  .col
    %h4= "MIN: #{@min_temp}°C"
  .col
    %h4= "MAX: #{@max_temp}°C"
  .col
    %h4= "Gef. #{@feels_like}°C"
  .col
  .col
%div.mt-5
  .row
    .col
      %div.mt-5
        %h2= @word.lt
      %div.mt-3
        %h2= @word.de
    .col
      %h3 Deutschland
      .mt-2
        - @news_german['articles'].first(5).each do |article|
          %h4= article['title']
          %p= article['content']
          %p= "(#{Date.parse article['publishedAt']})"
    .col
      %h3 Wirtschaft
      .mt-2
        - @news_economics['articles'].first(5).each do |article|
          %h4= article['title']
          %p= article['content']
          %p= "(#{article['publishedAt']})"

app/views/words/edit.html.haml
.mt-5
  = form_tag :word, method: :patch do
    .form-group
      = label_tag :lt, 'litauisch'
      = text_field_tag :lt, @word.lt, class: 'form-control'
    .form-group
      = label_tag :de, 'deutsch'
      = text_field_tag :de, @word.de, class: 'form-control'
    = submit_tag 'speichern', class: 'btn btn-primary'

app/views/words/index.html.haml
= link_to 'Wort hinzufügen', new_word_path, class: 'mb-5 btn btn-info mt-5'
%table.table
  %thead
    %th litauisch
    %th deutsch
    %th
  %tbody
    - @words.each do |word|
      %tr
        %td= word.lt
        %td= word.de
        %td
          =link_to 'ändern', edit_word_path(word)

app/views/words/new.html.haml
.mt-5
  = form_tag @word, method: :post do
    .form-group
      = label_tag :lt, 'litauisch'
      = text_field_tag :lt, @word.lt, class: 'form-control'
    .form-group
      = label_tag :de, 'deutsch'
      = text_field_tag :de, @word.de, class: 'form-control'
    = submit_tag 'speichern', class: 'btn btn-primary'